language: perl
perl:
  - "5.26"
  - "dev"
env:
  - COVERAGE=1
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
  - cd cpan/Lingua-YALI; make development-requirements
before_script:
  - coverage-setup
script:
  - cd cpan/Lingua-YALI; prove -lrs t
after_success:
  - coverage-report
